apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: idysman/udagram-api-user:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-configmap
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-user-service
spec:
  selector:
    app: backend-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
