apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: idysman/udagram-frontend:v1
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
