apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: idysman/reverseproxy:v2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service
spec:
  type: LoadBalancer
  selector:
    app: reverseproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
