language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f ./docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed idysman/udagram-api-feed:v1
  - docker tag udagram-api-user idysman/udagram-api-user:v1
  - docker tag reverseproxy idysman/reverseproxy:v2
  - docker tag udagram-frontend idysman/udagram-frontend:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push idysman/udagram-api-feed:v1
  - docker push idysman/udagram-api-user:v1
  - docker push idysman/reverseproxy:v2
  - docker push idysman/udagram-frontend:v4
